server:
  port: 8080

spring:
  jms:
    pub-sub-domain: true
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10
    requests:
      topic: topic_requests
    replies:
      topic: topic_replies
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1127.0.0.1:3306/test
    username: test
    password: [Encrypted]
    hikari:
      maximum-pool-size: 10
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/test?gssapiServiceName=mongodb


  batch:
    job:
      enabled: false
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            clusterCheckinInterval: 10000
            useProperties: false
            selectWithLockSQL: SELECT * FROM {0}LOCKS UPDLOCK WHERE LOCK_NAME = ?
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
